spring:
  application:
    name: LearnSpringBoot
  profiles:
      active: dev
#
open:
  api:
    description: api-service
    title: API Service
    version: v1.0.0
    serverUrl: http://localhost:8080
    serverName: server test